# Ubuntu version codename (focal, jammy)
ARG UBUNTU_CODENAME=noble

# NeuroDebian image to copy configuration from
# http://neuro.debian.net/
FROM neurodebian:${UBUNTU_CODENAME}-non-free AS neurodebian
 
# Micromamba base image
# https://mamba.readthedocs.io/
# https://micromamba-docker.readthedocs.io/
FROM mambaorg/micromamba:${UBUNTU_CODENAME}
ARG MAMBA_DOCKERFILE_ACTIVATE=1
USER 0
RUN mkdir /workspace
#RUN chown -R ${MAMBA_USER} /workspace

#USER ${MAMBA_USER}
COPY .devcontainer/environment.yml ./
RUN : \
  && micromamba install --yes --name "base" --file environment.yml \
  && micromamba clean --all --yes
# throws away unused packages, wipes cache

